### ISSUE TITLE
Unable run export multiple

### ISSUE THREAD

**Issue by ngiger** [netceteragroup/trema-maven#2]
I am trying to use Trema for the translation of our Eclipse RCP application Elexis (www.elexis.info). 

I want to two use one trm file for generating the plugin.properties and another one for the messages.properites and tried it with the attached pom.xml
[pom.xml.txt](https://github.com/netceteragroup/trema-maven/files/737740/pom.xml.txt)

Calling mvn clean trema:exportProperties (I use version 3.0.5) however always uses the global configuration and never the configuration specific for a given executions.

**Comment by stadler** [comment]
Hi ngiger

This is the intended behavior according to the maven documentation:
https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_executions_Tag

> Note: Configurations inside the <executions> tag differ from those that are outside <executions> in that they cannot be used from a direct command line invocation. Instead they are only applied when the lifecycle phase they are bound to are invoked. Alternatively, if you move a configuration section outside of the executions section, it will apply globally to all invocations of the plugin.

Therefore explicitly invoking the plugin goal (`mvn trema:exportProperties`) won't work with configurations within the execution. You will probably have to call it through it's associated lifecycle phase `mvn process-resources`.

Hope that helps. Otherwise feel free to reopen the issue.

**Comment by ngiger** [comment]
Thanks for your suggestion. This fixed my problem. I would appreciate if you could add a sentence like
"Used the mavne process-resources to write both properties."
